
services:
  mysql:   # 必须在 services 下面！
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shuan
    ports:
      - "3306:3306"
    volumes:
      - /root/mysql/data:/var/lib/mysql
      - /root/mysql/mysql-config/my.cnf:/etc/mysql/my.cnf
    networks:
      - mynetwork
volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
