
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /root/es/data:/usr/share/elasticsearch/data
    networks:
      - mynetwork
    mem_limit: 1g  # 限制最大内存 1GB
    cpus: "1.0"  # 限制 CPU 使用 1 核心

networks:
  mynetwork:
    driver: bridge
